---
- name: Deploy a Kafka container with Podman using KRaft mode (Fixed)
  hosts: all
  become: true
  vars:
    kafka_container_name: cp-kafka
    kafka_image: "docker.io/confluentinc/cp-kafka:7.9.0"
    kafka_memory_limit: "4096m"
    kafka_port: 9092
    kafka_controller_port: 9093
    kafka_data_dir: /var/lib/kafka/data
    kafka_tmp_dir: /tmp/kafka-setup-{{ ansible_date_time.epoch }}

  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
          - podman
          - python3-podman
        state: present

    - name: Create unique temporary directory
      ansible.builtin.file:
        path: "{{ kafka_tmp_dir }}"
        state: directory
        mode: '0755'

    - name: Ensure Kafka data directory is completely removed
      ansible.builtin.file:
        path: "{{ kafka_data_dir }}"
        state: absent

    - name: Recreate Kafka data directory
      ansible.builtin.file:
        path: "{{ kafka_data_dir }}"
        state: directory
        owner: "1000"
        group: "1000"
        mode: '0755'

    - name: Ensure Podman network for Kafka exists
      containers.podman.podman_network:
        name: kafka-network
        state: present

    - name: Remove existing Kafka container if it exists
      containers.podman.podman_container:
        name: "{{ kafka_container_name }}"
        state: absent
      ignore_errors: yes

    - name: Generate Kafka Cluster ID inside the container
      ansible.builtin.command:
        cmd: "podman run --rm {{ kafka_image }} /usr/bin/kafka-storage random-uuid"
      register: generated_cluster_id
      changed_when: false

    - name: Display Generated Cluster ID
      ansible.builtin.debug:
        msg: "Generated Cluster ID: {{ generated_cluster_id.stdout }}"

    - name: Format Kafka storage inside the container
      ansible.builtin.command:
        cmd: >
          podman run --rm -v {{ kafka_data_dir }}:/var/lib/kafka/data:Z {{ kafka_image }}
          /usr/bin/kafka-storage format --cluster-id {{ generated_cluster_id.stdout }} --config /etc/kafka/kraft/server.properties
      register: format_result

    - name: Display Format Result
      ansible.builtin.debug:
        var: format_result.stdout_lines

    - name: Start Kafka container with KRaft mode
      containers.podman.podman_container:
        name: "{{ kafka_container_name }}"
        image: "{{ kafka_image }}"
        state: started
        detach: true
        memory: "{{ kafka_memory_limit }}"
        hostname: kafka
        publish:
          - "{{ kafka_port }}:{{ kafka_port }}"
          - "{{ kafka_controller_port }}:{{ kafka_controller_port }}"
          - "29092:29092"
        restart_policy: always
        network: kafka-network
        volume:
          - "{{ kafka_data_dir }}:/var/lib/kafka/data:Z"

    - name: Wait for Kafka to initialize
      ansible.builtin.pause:
        seconds: 20

    - name: Verify Kafka is running by listing topics
      ansible.builtin.command:
        cmd: "podman exec {{ kafka_container_name }} kafka-topics --list --bootstrap-server localhost:9092"
      register: topic_list
      changed_when: false
      retries: 3
      delay: 5
      until: topic_list.rc == 0

    - name: Display Kafka Topics
      ansible.builtin.debug:
        var: topic_list.stdout_lines
